window.STACKNSTOCK_DATA = {
  "rows": [
    {
      "id": "row-2",
      "poDate": "2026-02-12",
      "deliveryDate": "2026-03-02",
      "deliveryStatus": null,
      "poNumber": "PO-00006",
      "reference": "",
      "poStatus": "Billed",
      "vendorName": "PERFECT FABRICATORS",
      "hsnSac": "",
      "source": "MH",
      "gstin": "27AAPPJ2103E1Z3",
      "referenceNo": "",
      "terms": "Payment Terms: 50% advance and 50% against Proforma Invoice before dispatch.\n\nDelivery Period: 10–12 working days.\n\nQuality: Maintain the same quality as agreed upon.",
      "itemPrice": 930,
      "itemDesc": "70 X 20 SS/PU Drive Wheel (MOC Insert : SS304, MOC Coating : Polyurethane 95 A, Shfat Dia 13mm Keyway : 5.25 mm, Color RED, Size : As Per drawing)",
      "quantityOrdered": 8,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 1339.2,
      "itemTotal": 7440,
      "total": 18768,
      "paymentStatus": "Paid",
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-3",
      "poDate": "2026-02-12",
      "deliveryDate": "2026-03-02",
      "deliveryStatus": null,
      "poNumber": "PO-00006",
      "reference": "",
      "poStatus": "Billed",
      "vendorName": "PERFECT FABRICATORS",
      "hsnSac": "",
      "source": "MH",
      "gstin": "27AAPPJ2103E1Z3",
      "referenceNo": "",
      "terms": "Payment Terms: 50% advance and 50% against Proforma Invoice before dispatch.\n\nDelivery Period: 10–12 working days.\n\nQuality: Maintain the same quality as agreed upon.",
      "itemPrice": 985,
      "itemDesc": "70 X 20 SS/PU Idler Wheel (MOC Insert : SS304, MOC Coating : Polyurethane 95 A, As Per drawing, Bearing Size 6001, Bearing ID 12mm, Color RED)",
      "quantityOrdered": 8,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 1418.4,
      "itemTotal": 7880,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-4",
      "poDate": "2026-02-12",
      "deliveryDate": "2026-03-02",
      "deliveryStatus": "idk",
      "poNumber": "PO-00006",
      "reference": "",
      "poStatus": "Billed",
      "vendorName": "PERFECT FABRICATORS",
      "hsnSac": "",
      "source": "MH",
      "gstin": "27AAPPJ2103E1Z3",
      "referenceNo": "",
      "terms": "Payment Terms: 50% advance and 50% against Proforma Invoice before dispatch.\n\nDelivery Period: 10–12 working days.\n\nQuality: Maintain the same quality as agreed upon.",
      "itemPrice": 585,
      "itemDesc": "Freight Charges",
      "quantityOrdered": 1,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 105.3,
      "itemTotal": 585,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-5",
      "poDate": "2026-02-13",
      "deliveryDate": "2026-02-16",
      "deliveryStatus": null,
      "poNumber": "PO-00009",
      "reference": "",
      "poStatus": "Billed",
      "vendorName": "Shivam Steel",
      "hsnSac": "",
      "source": "KL",
      "gstin": "32CCQPC0620Q1ZL",
      "referenceNo": "",
      "terms": "Quality: Maintain the same quality as agreed upon.",
      "itemPrice": 1186,
      "itemDesc": "14MM ROUND ROD -304 GRADE 900MM LENGTH, h8 diametric tolerance.",
      "quantityOrdered": 2,
      "itemTax": "GST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 426.96,
      "itemTotal": 2372,
      "total": 2799,
      "paymentStatus": "Paid",
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-6",
      "poDate": "2026-02-23",
      "deliveryDate": "2026-04-06",
      "deliveryStatus": null,
      "poNumber": "PO-00010",
      "reference": "",
      "poStatus": "Billed",
      "vendorName": "Belcon",
      "hsnSac": "",
      "source": "MH",
      "gstin": "27AARFB0427H1ZH",
      "referenceNo": "",
      "terms": "Delivery : Within 5 - 6 weeks.\nQuality: Maintain the same quality as agreed upon.\nPayment: 50% Advance and balance before dispatch.",
      "itemPrice": 2020,
      "itemDesc": "TRANSTEC Self Track Timing Pulley \nDriver Pulley, with self tracking ring (STR-32AT5) \nPulley Material : EN AW 6082 T6",
      "quantityOrdered": 4,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 1454.4,
      "itemTotal": 8080,
      "total": 47243,
      "paymentStatus": "Paid",
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-7",
      "poDate": "2026-02-23",
      "deliveryDate": "2026-04-06",
      "deliveryStatus": null,
      "poNumber": "PO-00010",
      "reference": "",
      "poStatus": "Billed",
      "vendorName": "Belcon",
      "hsnSac": "",
      "source": "MH",
      "gstin": "27AARFB0427H1ZH",
      "referenceNo": "",
      "terms": "Delivery : Within 5 - 6 weeks.\nQuality: Maintain the same quality as agreed upon.\nPayment: 50% Advance and balance before dispatch.",
      "itemPrice": 1650,
      "itemDesc": "TRANSTEC Self Track Timing Pulley \nDriven Pulley, with self tracking ring (STR-32AT5) \nPulley Material : EN AW 6082 T6",
      "quantityOrdered": 4,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 1188,
      "itemTotal": 6600,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-8",
      "poDate": "2026-02-23",
      "deliveryDate": "2026-04-06",
      "deliveryStatus": null,
      "poNumber": "PO-00010",
      "reference": "",
      "poStatus": "Billed",
      "vendorName": "Belcon",
      "hsnSac": "",
      "source": "MH",
      "gstin": "27AARFB0427H1ZH",
      "referenceNo": "",
      "terms": "Delivery : Within 5 - 6 weeks.\nQuality: Maintain the same quality as agreed upon.\nPayment: 50% Advance and balance before dispatch.",
      "itemPrice": 5050,
      "itemDesc": "PU Open Timing Belt (With Self Track Groove)\n25AT5/5000-M PAZ + ST Groove (Open) ",
      "quantityOrdered": 4,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 3636,
      "itemTotal": 20200,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-9",
      "poDate": "2026-02-23",
      "deliveryDate": "2026-04-06",
      "deliveryStatus": null,
      "poNumber": "PO-00010",
      "reference": "",
      "poStatus": "Billed",
      "vendorName": "Belcon",
      "hsnSac": "",
      "source": "MH",
      "gstin": "27AARFB0427H1ZH",
      "referenceNo": "",
      "terms": "Delivery : Within 5 - 6 weeks.\nQuality: Maintain the same quality as agreed upon.\nPayment: 50% Advance and balance before dispatch.",
      "itemPrice": 530,
      "itemDesc": "TRANSTEC Clamping Plate - CP AT5 25 model.",
      "quantityOrdered": 4,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 381.6,
      "itemTotal": 2120,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-10",
      "poDate": "2026-02-23",
      "deliveryDate": "2026-04-06",
      "deliveryStatus": null,
      "poNumber": "PO-00010",
      "reference": "",
      "poStatus": "Billed",
      "vendorName": "Belcon",
      "hsnSac": "",
      "source": "MH",
      "gstin": "27AARFB0427H1ZH",
      "referenceNo": "",
      "terms": "Delivery : Within 5 - 6 weeks.\nQuality: Maintain the same quality as agreed upon.\nPayment: 50% Advance and balance before dispatch.",
      "itemPrice": 759,
      "itemDesc": "Keyless Locking Device XY01 - 14 X 26",
      "quantityOrdered": 4,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 546.48,
      "itemTotal": 3036,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-11",
      "poDate": "2026-02-25",
      "deliveryDate": "2026-03-07",
      "deliveryStatus": null,
      "poNumber": "PO-00011",
      "reference": "LB111F9GGD",
      "poStatus": "Billed",
      "vendorName": "Misumi India Pvt Ltd",
      "hsnSac": "",
      "source": "KA",
      "gstin": "29AAFCM9345Q1ZI",
      "referenceNo": "LB111F9GGD",
      "terms": "",
      "itemPrice": 783,
      "itemDesc": "SHA20\nSHAFT HOLDER\nWeight 328g\nHS CODE CHN73269099",
      "quantityOrdered": 4,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 563.76,
      "itemTotal": 3132,
      "total": 17256.7,
      "paymentStatus": "Paid",
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-12",
      "poDate": "2026-02-25",
      "deliveryDate": "2026-03-07",
      "deliveryStatus": null,
      "poNumber": "PO-00011",
      "reference": "LB111F9GGD",
      "poStatus": "Billed",
      "vendorName": "Misumi India Pvt Ltd",
      "hsnSac": "",
      "source": "KA",
      "gstin": "29AAFCM9345Q1ZI",
      "referenceNo": "LB111F9GGD",
      "terms": "",
      "itemPrice": 654.23,
      "itemDesc": "HMHSU30-16\nROLLERS\nWeight 240g\nHS CODE JPN84835090",
      "quantityOrdered": 8,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 942.09,
      "itemTotal": 5233.84,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-13",
      "poDate": "2026-02-25",
      "deliveryDate": "2026-03-07",
      "deliveryStatus": null,
      "poNumber": "PO-00011",
      "reference": "LB111F9GGD",
      "poStatus": "Billed",
      "vendorName": "Misumi India Pvt Ltd",
      "hsnSac": "",
      "source": "KA",
      "gstin": "29AAFCM9345Q1ZI",
      "referenceNo": "LB111F9GGD",
      "terms": "",
      "itemPrice": 1106.36,
      "itemDesc": "EN14\nNSK BEARINGS(NSK)\nWeight 70g\nHS CODE JPN84828000",
      "quantityOrdered": 2,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 398.29,
      "itemTotal": 2212.72,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-14",
      "poDate": "2026-02-25",
      "deliveryDate": "2026-03-07",
      "deliveryStatus": null,
      "poNumber": "PO-00011",
      "reference": "LB111F9GGD",
      "poStatus": "Billed",
      "vendorName": "Misumi India Pvt Ltd",
      "hsnSac": "",
      "source": "KA",
      "gstin": "29AAFCM9345Q1ZI",
      "referenceNo": "LB111F9GGD",
      "terms": "",
      "itemPrice": 342.72,
      "itemDesc": "C-SE6809ZZ\nBEARINGS\nWeight 304g\nHS CODE CHN84821090",
      "quantityOrdered": 8,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 493.52,
      "itemTotal": 2741.76,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-15",
      "poDate": "2026-02-25",
      "deliveryDate": "2026-03-07",
      "deliveryStatus": null,
      "poNumber": "PO-00011",
      "reference": "LB111F9GGD",
      "poStatus": "Billed",
      "vendorName": "Misumi India Pvt Ltd",
      "hsnSac": "",
      "source": "KA",
      "gstin": "29AAFCM9345Q1ZI",
      "referenceNo": "LB111F9GGD",
      "terms": "",
      "itemPrice": 163,
      "itemDesc": "C-SE6904ZZ\nBEARINGS\nWeight 288g\nHS CODE CHN84821090",
      "quantityOrdered": 8,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 234.72,
      "itemTotal": 1304,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-16",
      "poDate": "2026-02-25",
      "deliveryDate": "2026-03-10",
      "deliveryStatus": null,
      "poNumber": "PO-00012",
      "reference": "LB111FA1DE",
      "poStatus": "Billed",
      "vendorName": "Misumi India Pvt Ltd",
      "hsnSac": "",
      "source": "KA",
      "gstin": "29AAFCM9345Q1ZI",
      "referenceNo": "LB111FA1DE",
      "terms": "",
      "itemPrice": 430.3,
      "itemDesc": "C-SCSBNAW20-24\nSET COLLAR\nHS CODE CHN76169990",
      "quantityOrdered": 8,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 619.63,
      "itemTotal": 3442.4,
      "total": 4062.03,
      "paymentStatus": "Paid",
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-17",
      "poDate": "2026-02-27",
      "deliveryDate": "",
      "deliveryStatus": "2026-03-30",
      "poNumber": "PO-00013",
      "reference": "S6317187",
      "poStatus": "Billed",
      "vendorName": "Automatix",
      "hsnSac": "",
      "source": "KL",
      "gstin": "32AAJFA3705B1Z8",
      "referenceNo": "S6317187",
      "terms": "Payment Terms\n50% Advance, balance against PI \n\nDelivery Terms\nWill be picked up by customer\n\nInspection & Acceptance\nSubject to item specification and performance compliance.\n\nWarranty\n12 months against manufacturing defects.",
      "itemPrice": 168,
      "itemDesc": "PGR 63X58X6.3-PF – SKF Guide Ring",
      "quantityOrdered": 16,
      "itemTax": "GST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 483.84,
      "itemTotal": 2688,
      "total": 3171.84,
      "paymentStatus": "PartiallyPaid",
      "balanceDue": 1586.84,
      "manual": false
    },
    {
      "id": "row-18",
      "poDate": "2026-02-27",
      "deliveryDate": "2026-03-14",
      "deliveryStatus": "idk",
      "poNumber": "PO-00014",
      "reference": "1 dt. 27-Feb-26",
      "poStatus": "Billed",
      "vendorName": "Shivam Steel",
      "hsnSac": "",
      "source": "KL",
      "gstin": "32CCQPC0620Q1ZL",
      "referenceNo": "1 dt. 27-Feb-26",
      "terms": "Quality: Maintain the same quality as agreed upon.\n\nPayment: Full payment of Item No:1 and 50% of Item No:2 on confirming of PO. The balance amount shall be paid on dispatch.",
      "itemPrice": 325,
      "itemDesc": "S S PIPES -7306400\n21*2MM(1/2 Sch-10)-2 Mtr",
      "quantityOrdered": 2,
      "itemTax": "GST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 117,
      "itemTotal": 650,
      "total": 17537,
      "paymentStatus": "PartiallyPaid",
      "balanceDue": 8768,
      "manual": false
    },
    {
      "id": "row-19",
      "poDate": "2026-02-27",
      "deliveryDate": "2026-03-14",
      "deliveryStatus": "idk",
      "poNumber": "PO-00014",
      "reference": "1 dt. 27-Feb-26",
      "poStatus": "Billed",
      "vendorName": "Shivam Steel",
      "hsnSac": "",
      "source": "KL",
      "gstin": "32CCQPC0620Q1ZL",
      "referenceNo": "1 dt. 27-Feb-26",
      "terms": "Quality: Maintain the same quality as agreed upon.\n\nPayment: Full payment of Item No:1 and 50% of Item No:2 on confirming of PO. The balance amount shall be paid on dispatch.",
      "itemPrice": 1292,
      "itemDesc": "S S PIPES-NOS\n25*10",
      "quantityOrdered": 11,
      "itemTax": "GST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 2558.16,
      "itemTotal": 14212,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-20",
      "poDate": "2026-03-02",
      "deliveryDate": "2026-03-12",
      "deliveryStatus": "2026-03-27",
      "poNumber": "PO-00015",
      "reference": "SC- 1892/02-19",
      "poStatus": "Issued",
      "vendorName": "Santhosh Composite Pvt Ltd",
      "hsnSac": "",
      "source": "KL",
      "gstin": "32ABHCS0581P1ZZ",
      "referenceNo": "SC- 1892/02-19",
      "terms": "Supply strictly as per PO specifications and quantities.\nPrices as per PO (GST included where specified). Ex-Works unless agreed otherwise.\n50% advance against PO/PI; balance 50% before dispatch.\nDelivery within agreed timeline from date of advance. Deliver to site as instructed.\nMaterial subject to site inspection. Non-conforming or damaged goods to be replaced at supplier’s cost.\nSupplier to provide GST invoice and required transport documents. Disputes subject to Kerala jurisdiction.",
      "itemPrice": 875,
      "itemDesc": "FRP Rect Box 101.6 x 50.8 x 6.35mm thk, 3700mm L, Grey RAL 7040",
      "quantityOrdered": 7.4,
      "itemTax": "GST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 1150.24,
      "itemTotal": 6390.18,
      "total": 57000,
      "paymentStatus": "PartiallyPaid",
      "balanceDue": 37000,
      "manual": false
    },
    {
      "id": "row-21",
      "poDate": "2026-03-02",
      "deliveryDate": "2026-03-12",
      "deliveryStatus": "2026-03-27",
      "poNumber": "PO-00015",
      "reference": "SC- 1892/02-19",
      "poStatus": "Issued",
      "vendorName": "Santhosh Composite Pvt Ltd",
      "hsnSac": "",
      "source": "KL",
      "gstin": "32ABHCS0581P1ZZ",
      "referenceNo": "SC- 1892/02-19",
      "terms": "Supply strictly as per PO specifications and quantities.\nPrices as per PO (GST included where specified). Ex-Works unless agreed otherwise.\n50% advance against PO/PI; balance 50% before dispatch.\nDelivery within agreed timeline from date of advance. Deliver to site as instructed.\nMaterial subject to site inspection. Non-conforming or damaged goods to be replaced at supplier’s cost.\nSupplier to provide GST invoice and required transport documents. Disputes subject to Kerala jurisdiction.",
      "itemPrice": 350,
      "itemDesc": "FRP Rect Box 75 x 45 x 3mm thk, 2500mm L, Grey RAL 7035",
      "quantityOrdered": 15,
      "itemTax": "GST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 932.62,
      "itemTotal": 5181.22,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-22",
      "poDate": "2026-03-02",
      "deliveryDate": "2026-03-12",
      "deliveryStatus": "2026-03-27",
      "poNumber": "PO-00015",
      "reference": "SC- 1892/02-19",
      "poStatus": "Issued",
      "vendorName": "Santhosh Composite Pvt Ltd",
      "hsnSac": "",
      "source": "KL",
      "gstin": "32ABHCS0581P1ZZ",
      "referenceNo": "SC- 1892/02-19",
      "terms": "Supply strictly as per PO specifications and quantities.\nPrices as per PO (GST included where specified). Ex-Works unless agreed otherwise.\n50% advance against PO/PI; balance 50% before dispatch.\nDelivery within agreed timeline from date of advance. Deliver to site as instructed.\nMaterial subject to site inspection. Non-conforming or damaged goods to be replaced at supplier’s cost.\nSupplier to provide GST invoice and required transport documents. Disputes subject to Kerala jurisdiction.",
      "itemPrice": 350,
      "itemDesc": "FRP Rect Box 75 x 45 x 3mm thk, 420mm L, Grey RAL 7035",
      "quantityOrdered": 3.36,
      "itemTax": "GST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 208.9,
      "itemTotal": 1160.59,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-23",
      "poDate": "2026-03-02",
      "deliveryDate": "2026-03-12",
      "deliveryStatus": "2026-03-27",
      "poNumber": "PO-00015",
      "reference": "SC- 1892/02-19",
      "poStatus": "Issued",
      "vendorName": "Santhosh Composite Pvt Ltd",
      "hsnSac": "",
      "source": "KL",
      "gstin": "32ABHCS0581P1ZZ",
      "referenceNo": "SC- 1892/02-19",
      "terms": "Supply strictly as per PO specifications and quantities.\nPrices as per PO (GST included where specified). Ex-Works unless agreed otherwise.\n50% advance against PO/PI; balance 50% before dispatch.\nDelivery within agreed timeline from date of advance. Deliver to site as instructed.\nMaterial subject to site inspection. Non-conforming or damaged goods to be replaced at supplier’s cost.\nSupplier to provide GST invoice and required transport documents. Disputes subject to Kerala jurisdiction.",
      "itemPrice": 445,
      "itemDesc": "FRP Channel 100 x 30 x 6mm thk, 3000mm L, Grey RAL 7035",
      "quantityOrdered": 81,
      "itemTax": "GST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 6403.1,
      "itemTotal": 35572.81,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-24",
      "poDate": "2026-03-02",
      "deliveryDate": "",
      "deliveryStatus": null,
      "poNumber": "PO-00016",
      "reference": "24-25/267",
      "poStatus": "Billed",
      "vendorName": "VEDANT INDUSTRIES",
      "hsnSac": "8302",
      "source": "MH",
      "gstin": "27BRJPM3558A1ZT",
      "referenceNo": "24-25/267",
      "terms": "",
      "itemPrice": 98,
      "itemDesc": "Pivot Connector 20x20",
      "quantityOrdered": 12,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 211.68,
      "itemTotal": 1176,
      "total": 14816,
      "paymentStatus": "PartiallyPaid",
      "balanceDue": 7408,
      "manual": false
    },
    {
      "id": "row-25",
      "poDate": "2026-03-02",
      "deliveryDate": "",
      "deliveryStatus": null,
      "poNumber": "PO-00016",
      "reference": "24-25/267",
      "poStatus": "Billed",
      "vendorName": "VEDANT INDUSTRIES",
      "hsnSac": "7326",
      "source": "MH",
      "gstin": "27BRJPM3558A1ZT",
      "referenceNo": "24-25/267",
      "terms": "",
      "itemPrice": 8,
      "itemDesc": "20x20 T Nut M5",
      "quantityOrdered": 200,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 288,
      "itemTotal": 1600,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-26",
      "poDate": "2026-03-02",
      "deliveryDate": "",
      "deliveryStatus": null,
      "poNumber": "PO-00016",
      "reference": "24-25/267",
      "poStatus": "Billed",
      "vendorName": "VEDANT INDUSTRIES",
      "hsnSac": "4016",
      "source": "MH",
      "gstin": "27BRJPM3558A1ZT",
      "referenceNo": "24-25/267",
      "terms": "",
      "itemPrice": 10,
      "itemDesc": " 20x20 End Cap",
      "quantityOrdered": 15,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 27,
      "itemTotal": 150,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-27",
      "poDate": "2026-03-02",
      "deliveryDate": "",
      "deliveryStatus": null,
      "poNumber": "PO-00016",
      "reference": "24-25/267",
      "poStatus": "Billed",
      "vendorName": "VEDANT INDUSTRIES",
      "hsnSac": "7616",
      "source": "MH",
      "gstin": "27BRJPM3558A1ZT",
      "referenceNo": "24-25/267",
      "terms": "",
      "itemPrice": 15,
      "itemDesc": "20x20 Angle Bracket",
      "quantityOrdered": 20,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 54,
      "itemTotal": 300,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-28",
      "poDate": "2026-03-02",
      "deliveryDate": "",
      "deliveryStatus": null,
      "poNumber": "PO-00016",
      "reference": "24-25/267",
      "poStatus": "Billed",
      "vendorName": "VEDANT INDUSTRIES",
      "hsnSac": "76042990",
      "source": "MH",
      "gstin": "27BRJPM3558A1ZT",
      "referenceNo": "24-25/267",
      "terms": "",
      "itemPrice": 280,
      "itemDesc": "Alu Profile (20x20)",
      "quantityOrdered": 21,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 1058.4,
      "itemTotal": 5880,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-29",
      "poDate": "2026-03-02",
      "deliveryDate": "",
      "deliveryStatus": null,
      "poNumber": "PO-00016",
      "reference": "24-25/267",
      "poStatus": "Billed",
      "vendorName": "VEDANT INDUSTRIES",
      "hsnSac": "7326",
      "source": "MH",
      "gstin": "27BRJPM3558A1ZT",
      "referenceNo": "24-25/267",
      "terms": "",
      "itemPrice": 50,
      "itemDesc": "20X20 L JOINTER",
      "quantityOrdered": 20,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 180,
      "itemTotal": 1000,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-30",
      "poDate": "2026-03-02",
      "deliveryDate": "",
      "deliveryStatus": null,
      "poNumber": "PO-00016",
      "reference": "24-25/267",
      "poStatus": "Billed",
      "vendorName": "VEDANT INDUSTRIES",
      "hsnSac": "7326",
      "source": "MH",
      "gstin": "27BRJPM3558A1ZT",
      "referenceNo": "24-25/267",
      "terms": "",
      "itemPrice": 55,
      "itemDesc": "20X20 T JOINTER",
      "quantityOrdered": 30,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 297,
      "itemTotal": 1650,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-31",
      "poDate": "2026-03-02",
      "deliveryDate": "",
      "deliveryStatus": null,
      "poNumber": "PO-00016",
      "reference": "24-25/267",
      "poStatus": "Billed",
      "vendorName": "VEDANT INDUSTRIES",
      "hsnSac": "9988",
      "source": "MH",
      "gstin": "27BRJPM3558A1ZT",
      "referenceNo": "24-25/267",
      "terms": "",
      "itemPrice": 800,
      "itemDesc": "PACKING CHARGES",
      "quantityOrdered": 1,
      "itemTax": "IGST18",
      "itemTaxPercent": "18.00",
      "itemTaxAmount": 144,
      "itemTotal": 800,
      "total": null,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-32",
      "poDate": "2026-03-06",
      "deliveryDate": "2026-03-13",
      "deliveryStatus": null,
      "poNumber": "PO-00017",
      "reference": "Voucher No. 11",
      "poStatus": "Issued",
      "vendorName": "TANISH ALUMINIUM INDUSTRIES",
      "hsnSac": 76082000,
      "source": "GJ",
      "gstin": "24AUWPS7959Q1Z1",
      "referenceNo": "Voucher No. 11",
      "terms": "Quality: Maintain the same quality as agreed upon.\n \n Payment Terms: Advance\n \n Delivery Date: Within ten days of placing order or payment",
      "itemPrice": 1026,
      "itemDesc": "ALUMINIUM PNEUMATIC TUBE\n 68 * 63 *705 M.M. LONG TUBES\n BUNDLE 01\n TOTAL 02 PCS",
      "quantityOrdered": 1.41,
      "itemTax": "IGST18",
      "itemTaxPercent": 18,
      "itemTaxAmount": 260.4,
      "itemTotal": 1446.66,
      "total": 2120,
      "paymentStatus": "PartiallyPaid",
      "balanceDue": 1060,
      "manual": false
    },
    {
      "id": "row-33",
      "poDate": "2026-03-18",
      "deliveryDate": "2026-04-22",
      "deliveryStatus": null,
      "poNumber": "PO-00018",
      "reference": null,
      "poStatus": "Billed",
      "vendorName": "SMD Gearbox Pvt. Ltd.",
      "hsnSac": null,
      "source": "MH",
      "gstin": "27AAFCN4835L1Z2",
      "referenceNo": null,
      "terms": "Payment Term: 100% against PI\n Warranty: 12 months",
      "itemPrice": 41000,
      "itemDesc": "SRAC65-10-14-50-70-M5(1:2SPE60-5) \n Winch – Lift | Ratio 10 | Output: Locknut | Input: With keyway | Remark: Locknut type Output",
      "quantityOrdered": 2,
      "itemTax": "IGST18",
      "itemTaxPercent": 18,
      "itemTaxAmount": 14760,
      "itemTotal": 82000,
      "total": 329598,
      "paymentStatus": "Paid",
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-34",
      "poDate": "2026-03-18",
      "deliveryDate": "2026-04-22",
      "deliveryStatus": null,
      "poNumber": "PO-00018",
      "reference": null,
      "poStatus": "Billed",
      "vendorName": "SMD Gearbox Pvt. Ltd.",
      "hsnSac": null,
      "source": "MH",
      "gstin": "27AAFCN4835L1Z2",
      "referenceNo": null,
      "terms": "Payment Term: 100% against PI\n Warranty: 12 months",
      "itemPrice": 41000,
      "itemDesc": "SRAS65-2S-5-14-50-70-M5 (1:1SPE60-5) Winch/Follower – Drive | Ratio 5 | Output: Solid Shaft (T) | Input: With keyway | Remark: Double Output Shaft (T-type)",
      "quantityOrdered": 4,
      "itemTax": "IGST18",
      "itemTaxPercent": 18,
      "itemTaxAmount": 29520,
      "itemTotal": 164000,
      "total": 329598,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-35",
      "poDate": "2026-03-18",
      "deliveryDate": "2026-04-22",
      "deliveryStatus": null,
      "poNumber": "PO-00018",
      "reference": null,
      "poStatus": "Billed",
      "vendorName": "SMD Gearbox Pvt. Ltd.",
      "hsnSac": null,
      "source": "MH",
      "gstin": "27AAFCN4835L1Z2",
      "referenceNo": null,
      "terms": "Payment Term: 100% against PI\n Warranty: 12 months",
      "itemPrice": 32000,
      "itemDesc": "SS40F-3-8-30-46-M5 Load Carriage – Belt Drive | Ratio 3 | Output: Clamp | Input: Clamp type Output",
      "quantityOrdered": 1,
      "itemTax": "IGST18",
      "itemTaxPercent": 18,
      "itemTaxAmount": 5760,
      "itemTotal": 32000,
      "total": 329598,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-36",
      "poDate": "2026-03-18",
      "deliveryDate": "2026-04-22",
      "deliveryStatus": null,
      "poNumber": "PO-00018",
      "reference": null,
      "poStatus": "Billed",
      "vendorName": "SMD Gearbox Pvt. Ltd.",
      "hsnSac": null,
      "source": "MH",
      "gstin": "27AAFCN4835L1Z2",
      "referenceNo": null,
      "terms": "Payment Term: 100% against PI\n Warranty: 12 months",
      "itemPrice": 1320,
      "itemDesc": "Freight Received",
      "quantityOrdered": 1,
      "itemTax": "IGST18",
      "itemTaxPercent": 18,
      "itemTaxAmount": 237.6,
      "itemTotal": 1320,
      "total": 329598,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-37",
      "poDate": "2026-04-04",
      "deliveryDate": null,
      "deliveryStatus": null,
      "poNumber": "PO-00023",
      "reference": null,
      "poStatus": "Issued",
      "vendorName": "Automatix",
      "hsnSac": null,
      "source": "KL",
      "gstin": "32AAJFA3705B1Z8",
      "referenceNo": null,
      "terms": null,
      "itemPrice": 271,
      "itemDesc": "PGR 63X57X13-PF – SKF GUIDE RING",
      "quantityOrdered": 8,
      "itemTax": "GST18",
      "itemTaxPercent": 18,
      "itemTaxAmount": 390.24,
      "itemTotal": 2168,
      "total": 2558,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    },
    {
      "id": "row-38",
      "poDate": "2026-04-08",
      "deliveryDate": null,
      "deliveryStatus": "idk",
      "poNumber": "PO-00024",
      "reference": null,
      "poStatus": "Issued",
      "vendorName": "VEDANT INDUSTRIES",
      "hsnSac": 7604,
      "source": "MH",
      "gstin": "27BRJPM3558A1ZT",
      "referenceNo": null,
      "terms": "Mode/Terms of Payment: Advance\n Dispatch Through: By Transport\n Destination: Kerala\n Terms of Delivery: Immediate\n Price basis / other charges: Not specified in the document (no freight/packing terms mentioned beyond the separate “Packing Charges” line item)",
      "itemPrice": 320,
      "itemDesc": "Alu Profile (20x20) V Slot\n 2.5 MM X4 NOS",
      "quantityOrdered": 12,
      "itemTax": "IGST18",
      "itemTaxPercent": 18,
      "itemTaxAmount": 691.2,
      "itemTotal": 3840,
      "total": 5003,
      "paymentStatus": "PartaillyPaid",
      "balanceDue": 2502,
      "manual": false
    },
    {
      "id": "row-39",
      "poDate": "2026-04-08",
      "deliveryDate": null,
      "deliveryStatus": "idk",
      "poNumber": "PO-00024",
      "reference": null,
      "poStatus": "Issued",
      "vendorName": "VEDANT INDUSTRIES",
      "hsnSac": null,
      "source": "MH",
      "gstin": "27BRJPM3558A1ZT",
      "referenceNo": null,
      "terms": "Mode/Terms of Payment: Advance\n Dispatch Through: By Transport\n Destination: Kerala\n Terms of Delivery: Immediate\n Price basis / other charges: Not specified in the document (no freight/packing terms mentioned beyond the separate “Packing Charges” line item)",
      "itemPrice": 400,
      "itemDesc": "PACKING CHARGES",
      "quantityOrdered": 1,
      "itemTax": "IGST18",
      "itemTaxPercent": 18,
      "itemTaxAmount": 72,
      "itemTotal": 400,
      "total": 5003,
      "paymentStatus": null,
      "balanceDue": null,
      "manual": false
    }
  ],
  "vendorSeeds": [
    {
      "vendorName": "PERFECT FABRICATORS",
      "contactPerson": "",
      "phone": "",
      "email": "",
      "website": "",
      "city": "",
      "source": "MH",
      "gstin": "27AAPPJ2103E1Z3",
      "defaultLeadTimeDays": "",
      "rating": "",
      "notes": ""
    },
    {
      "vendorName": "Shivam Steel",
      "contactPerson": "",
      "phone": "",
      "email": "",
      "website": "",
      "city": "",
      "source": "KL",
      "gstin": "32CCQPC0620Q1ZL",
      "defaultLeadTimeDays": "",
      "rating": "",
      "notes": ""
    },
    {
      "vendorName": "Belcon",
      "contactPerson": "",
      "phone": "",
      "email": "",
      "website": "",
      "city": "",
      "source": "MH",
      "gstin": "27AARFB0427H1ZH",
      "defaultLeadTimeDays": "",
      "rating": "",
      "notes": ""
    },
    {
      "vendorName": "Misumi India Pvt Ltd",
      "contactPerson": "",
      "phone": "",
      "email": "",
      "website": "",
      "city": "",
      "source": "KA",
      "gstin": "29AAFCM9345Q1ZI",
      "defaultLeadTimeDays": "",
      "rating": "",
      "notes": ""
    },
    {
      "vendorName": "Automatix",
      "contactPerson": "",
      "phone": "",
      "email": "",
      "website": "",
      "city": "",
      "source": "KL",
      "gstin": "32AAJFA3705B1Z8",
      "defaultLeadTimeDays": "",
      "rating": "",
      "notes": ""
    },
    {
      "vendorName": "Santhosh Composite Pvt Ltd",
      "contactPerson": "",
      "phone": "",
      "email": "",
      "website": "",
      "city": "",
      "source": "KL",
      "gstin": "32ABHCS0581P1ZZ",
      "defaultLeadTimeDays": "",
      "rating": "",
      "notes": ""
    },
    {
      "vendorName": "VEDANT INDUSTRIES",
      "contactPerson": "",
      "phone": "",
      "email": "",
      "website": "",
      "city": "",
      "source": "MH",
      "gstin": "27BRJPM3558A1ZT",
      "defaultLeadTimeDays": "",
      "rating": "",
      "notes": ""
    },
    {
      "vendorName": "TANISH ALUMINIUM INDUSTRIES",
      "contactPerson": "",
      "phone": "",
      "email": "",
      "website": "",
      "city": "",
      "source": "GJ",
      "gstin": "24AUWPS7959Q1Z1",
      "defaultLeadTimeDays": "",
      "rating": "",
      "notes": ""
    },
    {
      "vendorName": "SMD Gearbox Pvt. Ltd.",
      "contactPerson": "",
      "phone": "",
      "email": "",
      "website": "",
      "city": "",
      "source": "MH",
      "gstin": "27AAFCN4835L1Z2",
      "defaultLeadTimeDays": "",
      "rating": "",
      "notes": ""
    }
  ]
};
